### ISSUE TITLE
Compiling HHVM on Ubuntu 16.04

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#148]
### HHVM Version

HHVM 3.15 (rel) master/next branch 

Ubuntu reached end of life for 15.04 and 15.10. We need try to compile HHVM for Ubuntu 16.10 and check dependencies changes and other issues. Facebook still have not updated building documents

**Comment by brunoalr** [comment]
I tried and succeeded in compiling HHVM on x86 with gcc 5.x. (will edit this comment later to update the version)
One small difference is that php5 is not on Ubuntu default repositories anymore in favor of php7.

**Comment by racardoso** [comment]
@brunoalr That's good. I'm trying to compile on PPC64. Yes PHP 5 s not on Ubuntu default anymore i don't think that will be a problem replace the dependencies for PHP 7.0 i guess. Also libboost 1.55 is not on default repository anymore too. It's 1.58 now. If everything works fine we can update the docs

**Comment by racardoso** [comment]
Got lots of error on linking like bellow:
`error: undefined reference to 'boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'`

I'm trying to use boost 1.58 but i guess it's still unsupported i'll switch back to 1.55

**Comment by racardoso** [comment]
well i guess the problem is the abi change on GCC5: 
http://developerblog.redhat.com/2015/02/05/gcc5-and-the-c11-abi/

boost 1.58 is compiled with GCC5 so the abi is incompatible. Im  using gcc 4.8 to compile HHVM. I guess i have to switch back to 1.55 . I wonder when HHVM will move to a newer gcc version

**Comment by brunoalr** [comment]
@racardoso, isn't it better to compile HHVM with gcc 5.x instead?

**Comment by racardoso** [comment]
@brunoalr yes i just compile it yesterday with gcc 5.x and works. I remember that HHVM doesn't compile with gcc > 4.8 before. I guess i will close this task and update our docs.

**Comment by gut** [comment]
watch out for pointing out that the our port supports a not-yet-officially supported environment. I'd just stick with whatever official HHVM supports.

**Comment by racardoso** [comment]
@gut yes i will point it on our documents. Thanks

**Comment by gromero** [comment]
@gut Ubuntu 16.04 (Xenial Xerus) is an officially supported environment. Ubuntu 15.10 is EOL by now. Apparently the doc pages must get updated accordingly. I filed the following bugs to trigger an update:
https://github.com/hhvm/user-documentation/issues/353
https://github.com/hhvm/user-documentation/issues/354

**Comment by racardoso** [comment]
@gromero Thanks for opening the ticket for user-documentation. In fact in official hhvm docs do not have instructions to build from source on 16.04 and i forgot to try install it via ppa/apt-get

**Comment by gut** [comment]
@gromero : I meant officially supported as a HHVM build platform, not from Ubuntu's point of view :-)

However it looks like I'm wrong and they are supporting now. On your user documentation bug you pointed out they are building packages for the Xenial (16.04). Thanks

**Comment by gromero** [comment]
@gut "I meant officially supported as a HHVM build platform, not from Ubuntu's point of view :-)" => That's exactly what I meant:

**gromero:** hhvm-help Now that Ubuntu 15.10 is EOL, what is intended (in terms of supported distribution for compiling from source) regarding Ubuntu 16.04?
**simon_w:** gromero, 16.04 is supported
**Orvid:** We already have packages for 16.04, and will be releasing 3.15, which will be an LTS release, in the next few weeks.
**simon_w:** Orvid, so hurry up and update the test infra so my diff can land :p
**gromero:** simon_w: I said that based on https://docs.hhvm.com/hhvm/installation/building-from-source. But anyway Orvid shed some light on it.
**Orvid:** simon_w, Bug paulbiss about that; I have no idea what internal infra needs updating for it :P
**gromero:** simon_w, Orvid thanks
**Orvid:** If all else, I'll cherry-pick it into 3.15 and see what happens :D
**simon_w:** Orvid, it contains tests to make sure that the extension was built, so the test infra needs libpq+headers before it can be green :p
**Orvid:** Add a skipif file and it won't care :P
**gromero:** simon_w, Orvid if 16.04 is supported and we have packages for 16.04 already, why it is not listed here https://docs.hhvm.com/hhvm/installation/linux?
**simon_w:** Orvid, There's deliberately no skipif so that you find out if you break it again :p
**simon_w:** gromero, cause no one's gotten around to copy+pasting for 16.04
**Orvid:** gromero, Because the docs page hasn't been updated. File a bug against the docs repo for it (there's a link at the bottom of the page)
**Orvid:** File one against the building from source page as well
**gromero:** simon_w, hum, right. So in that case is there another (precise) way to verify it? 
**gromero:** Orvid, ack
**Orvid:** http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/
**Orvid:** ^ The actual built packages

@racardoso @gut np
