### ISSUE TITLE
HHVM does not compile with g++ 5.4.1 in Ubuntu 16.10 PPC64

### ISSUE THREAD

**Issue by brunoalr** [PPC64/hhvm#160]
I upgraded my machines to Ubuntu 16.10 and tried compiling hhvm to check if everything is ok. 

First tried compiling with g++ 6, which is the default in 16.10, and failed. 

Then tried g++-5. Besides having to compile boost 1.58 manually (Ubuntu 16.10 comes with version 1.61), I stumbled upon this error, which does not occur in x86_64:

```
In file included from /home/brosa/hhvm/hphp/runtime/base/heap-graph.cpp:21:0:
/home/brosa/hhvm/hphp/runtime/base/heap-scan.h: In function ‘void HPHP::scanRoots(F&, HPHP::type_scan::Scanner&) [with F = HPHP::{anonymous}::PtrFilter<HPHP::{anonymous}::RootMarker>]’:
/home/brosa/hhvm/hphp/runtime/base/heap-scan.h:303:3: error: PIC register clobbered by ‘r30’ in ‘asm’
   CALLEE_SAVED_BARRIER(); // ensure stack contains callee-saved registers
   ^
hphp/runtime/CMakeFiles/hphp_runtime_static.dir/build.make:1172: recipe for target 'hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/heap-graph.cpp.o' failed
make[2]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/heap-graph.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/brosa/hhvm/hphp/runtime/base/heap-collect.cpp:19:0:
/home/brosa/hhvm/hphp/runtime/base/heap-scan.h: In function ‘void HPHP::scanRoots(F&, HPHP::type_scan::Scanner&) [with F = HPHP::{anonymous}::Marker]’:
/home/brosa/hhvm/hphp/runtime/base/heap-scan.h:303:3: error: PIC register clobbered by ‘r30’ in ‘asm’
   CALLEE_SAVED_BARRIER(); // ensure stack contains callee-saved registers
   ^
hphp/runtime/CMakeFiles/hphp_runtime_static.dir/build.make:1148: recipe for target 'hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/heap-collect.cpp.o' failed
make[2]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/base/heap-collect.cpp.o] Error 1
CMakeFiles/Makefile2:1896: recipe for target 'hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all' failed
make[1]: *** [hphp/runtime/CMakeFiles/hphp_runtime_static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by racardoso** [comment]
Solved. Compiled with GCC 6.1. Toolchain people say's that we can't clobber r30 because it may use under some arcane situations. We can never clobber r30. The problem is that GCC older versions was not caught this.

Ubuntu 16.10 is not officially supported. But i managed how to build and run hhvm on Ubuntu 16.10 for POWER (but need to apply some patches). Wiki updated:
https://github.com/PPC64/hhvm/wiki/Install-on-Ubuntu-system-16.10-(Experimental) - See troubleshooting section for patches.

Closing this issue.
